version: '3.4'

services:
  sshtunneller:
    depends_on:
      - sshd-server-test
    image: dmcken/ssh-tunnel
    build:
      context: .
    ports:
      - "80:80"
      - "3306:3306"
    environment:
      - log_level=DEBUG
      - ssh_host=sshdservertest
      - ssh_port=2222
      - ssh_username=root
      #- ssh_password=This_Is_a_SSH_P4SSW0RD
      - ssh_private_key_password=12345
      - remote_bind_addresses=[('127.0.0.1', 80),('127.0.0.1', 3306)]
      - local_bind_addresses=[("0.0.0.0", 80),('0.0.0.0', 3306)]
    volumes:
      - ./sshd_server_test/keys:/private.key
    restart: always

  sshdservertest:
    image: panubo/sshd_sshtunneller
    build:
      context: ./sshd_server_test
    ports:
      - "2222:22"
    environment:
      SSH_ENABLE_ROOT: "true"
      TCP_FORWARDING: "true"
