version: '3.4'

services:
  ssh-tunnel:
    image: dmcken/ssh-tunnel:v0.0.9
    build:
      context: .
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - ./private.key:/private.key
    restart: unless-stopped
